[package]
name = "macos-term"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk4 = { version = "0.10.1", package = "gtk4" }
cocoa = "0.26.1"
objc2 = "0.6.3"
libloading = "0.8.9"
objc2-app-kit = "0.3.2"
core-foundation = "0.10.0"
glib = "0.21.3"


[build-dependencies]
# cc = "1.0"
